### ISSUE TITLE
Add wrapper for add_models to create ensemble from collection of files

### ISSUE THREAD

**Issue by gregmedlock** [gregmedlock/Medusa#11]
Add a wrapper for add_models that allows the user to provide a list of filenames (JSON object from cobrapy or SBML) to build an ensemble, rather than requiring them to parse their own files and chunk them into smaller groups of models to save memory.

**Comment by Tjmoutinho** [comment]
This would be useful, but it would also be advantageous to add a function that allows for the addition of a model to an existing ensemble.

**Comment by gregmedlock** [comment]
@Tjmoutinho Let me know if you're interested in tackling this -- if not, I'll put it on my todo list. Unless potential users want to use this functionality, I don't think there's any rush to get it done though.

 I can write a more detailed issue description that lists some of the test cases that are needed, but you could use the old strategy I had implemented as a guide for now (see the "iterative join" option): https://github.com/gregmedlock/Medusa/blob/9394c96b4c30bf173eb56cd4519cbf346859b6db/medusa/core/ensemble.py

The old code got the job done with the previous medusa data structure (just a cobra model and a dictionary of reaction states), but was fairly slow. Might need some clever strategies to ever make this approach desirable vs. just loading all your models into memory and using the existing ensemble construction function.

**Comment by Tjmoutinho** [comment]
I am, I'll take care of it as soon as possible! I'll let you know what I'm thinking, after taking a look at it.

**Comment by gregmedlock** [comment]
Closed by #34
